/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PdfsRouteImport } from './routes/pdfs'
import { Route as PapersRouteImport } from './routes/papers'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as KnowledgeGraphRouteImport } from './routes/knowledge-graph'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as CurriculumRouteImport } from './routes/curriculum'
import { Route as CodingRouteImport } from './routes/coding'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfsRoute = PdfsRouteImport.update({
  id: '/pdfs',
  path: '/pdfs',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersRoute = PapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeGraphRoute = KnowledgeGraphRouteImport.update({
  id: '/knowledge-graph',
  path: '/knowledge-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumRoute = CurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const CodingRoute = CodingRouteImport.update({
  id: '/coding',
  path: '/coding',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/assistant': typeof AssistantRoute
  '/bookmarks': typeof BookmarksRoute
  '/certifications': typeof CertificationsRoute
  '/coding': typeof CodingRoute
  '/curriculum': typeof CurriculumRoute
  '/interview': typeof InterviewRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/labs': typeof LabsRoute
  '/lessons': typeof LessonsRoute
  '/library': typeof LibraryRoute
  '/notes': typeof NotesRoute
  '/papers': typeof PapersRoute
  '/pdfs': typeof PdfsRoute
  '/progress': typeof ProgressRoute
  '/projects': typeof ProjectsRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/assistant': typeof AssistantRoute
  '/bookmarks': typeof BookmarksRoute
  '/certifications': typeof CertificationsRoute
  '/coding': typeof CodingRoute
  '/curriculum': typeof CurriculumRoute
  '/interview': typeof InterviewRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/labs': typeof LabsRoute
  '/lessons': typeof LessonsRoute
  '/library': typeof LibraryRoute
  '/notes': typeof NotesRoute
  '/papers': typeof PapersRoute
  '/pdfs': typeof PdfsRoute
  '/progress': typeof ProgressRoute
  '/projects': typeof ProjectsRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/assistant': typeof AssistantRoute
  '/bookmarks': typeof BookmarksRoute
  '/certifications': typeof CertificationsRoute
  '/coding': typeof CodingRoute
  '/curriculum': typeof CurriculumRoute
  '/interview': typeof InterviewRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/labs': typeof LabsRoute
  '/lessons': typeof LessonsRoute
  '/library': typeof LibraryRoute
  '/notes': typeof NotesRoute
  '/papers': typeof PapersRoute
  '/pdfs': typeof PdfsRoute
  '/progress': typeof ProgressRoute
  '/projects': typeof ProjectsRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/assistant'
    | '/bookmarks'
    | '/certifications'
    | '/coding'
    | '/curriculum'
    | '/interview'
    | '/knowledge-graph'
    | '/labs'
    | '/lessons'
    | '/library'
    | '/notes'
    | '/papers'
    | '/pdfs'
    | '/progress'
    | '/projects'
    | '/roadmap'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/assistant'
    | '/bookmarks'
    | '/certifications'
    | '/coding'
    | '/curriculum'
    | '/interview'
    | '/knowledge-graph'
    | '/labs'
    | '/lessons'
    | '/library'
    | '/notes'
    | '/papers'
    | '/pdfs'
    | '/progress'
    | '/projects'
    | '/roadmap'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/assistant'
    | '/bookmarks'
    | '/certifications'
    | '/coding'
    | '/curriculum'
    | '/interview'
    | '/knowledge-graph'
    | '/labs'
    | '/lessons'
    | '/library'
    | '/notes'
    | '/papers'
    | '/pdfs'
    | '/progress'
    | '/projects'
    | '/roadmap'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AssistantRoute: typeof AssistantRoute
  BookmarksRoute: typeof BookmarksRoute
  CertificationsRoute: typeof CertificationsRoute
  CodingRoute: typeof CodingRoute
  CurriculumRoute: typeof CurriculumRoute
  InterviewRoute: typeof InterviewRoute
  KnowledgeGraphRoute: typeof KnowledgeGraphRoute
  LabsRoute: typeof LabsRoute
  LessonsRoute: typeof LessonsRoute
  LibraryRoute: typeof LibraryRoute
  NotesRoute: typeof NotesRoute
  PapersRoute: typeof PapersRoute
  PdfsRoute: typeof PdfsRoute
  ProgressRoute: typeof ProgressRoute
  ProjectsRoute: typeof ProjectsRoute
  RoadmapRoute: typeof RoadmapRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdfs': {
      id: '/pdfs'
      path: '/pdfs'
      fullPath: '/pdfs'
      preLoaderRoute: typeof PdfsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers': {
      id: '/papers'
      path: '/papers'
      fullPath: '/papers'
      preLoaderRoute: typeof PapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-graph': {
      id: '/knowledge-graph'
      path: '/knowledge-graph'
      fullPath: '/knowledge-graph'
      preLoaderRoute: typeof KnowledgeGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum': {
      id: '/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coding': {
      id: '/coding'
      path: '/coding'
      fullPath: '/coding'
      preLoaderRoute: typeof CodingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AssistantRoute: AssistantRoute,
  BookmarksRoute: BookmarksRoute,
  CertificationsRoute: CertificationsRoute,
  CodingRoute: CodingRoute,
  CurriculumRoute: CurriculumRoute,
  InterviewRoute: InterviewRoute,
  KnowledgeGraphRoute: KnowledgeGraphRoute,
  LabsRoute: LabsRoute,
  LessonsRoute: LessonsRoute,
  LibraryRoute: LibraryRoute,
  NotesRoute: NotesRoute,
  PapersRoute: PapersRoute,
  PdfsRoute: PdfsRoute,
  ProgressRoute: ProgressRoute,
  ProjectsRoute: ProjectsRoute,
  RoadmapRoute: RoadmapRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
